# Generated by Django 5.0.6 on 2024-09-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_app', '0003_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comments/'),
        ),
    ]
